services:
  green-growth:
    container_name: green-growth.untypequicode.fr
    restart: always
    build: .
    volumes:
      - ./src/:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.green-growth.rule=Host(`green-growth.untypequicode.fr`)
      - traefik.http.services.green-growth.loadbalancer.server.port=3000
